/**
 * 앱 전체 에러 코드 상수
 *
 * 카테고리별로 구분하여 관리합니다.
 */
export const ERROR_CODES = {
  // 공통
  UNKNOWN: 'UNKNOWN',
  NETWORK_ERROR: 'NETWORK_ERROR',
  TIMEOUT: 'TIMEOUT',

  // 인증 (Auth)
  USER_CANCELLED: 'USER_CANCELLED',
  AUTH_CANCELLED: 'AUTH_CANCELLED',
  AUTH_FAILED: 'AUTH_FAILED',
  GOOGLE_PLAY_NOT_AVAILABLE: 'GOOGLE_PLAY_NOT_AVAILABLE',

  // 콘텐츠 (Content)
  CONTENT_FETCH_ERROR: 'CONTENT_FETCH_ERROR',
  CONTENT_NOT_FOUND: 'CONTENT_NOT_FOUND',
  VIDEO_FETCH_ERROR: 'VIDEO_FETCH_ERROR',
  SEARCH_ERROR: 'SEARCH_ERROR',

  // 채널 (Channel)
  CHANNEL_FETCH_ERROR: 'CHANNEL_FETCH_ERROR',

  // TMDB
  TMDB_FETCH_ERROR: 'TMDB_FETCH_ERROR',

  // YouTube
  YOUTUBE_INVALID_URL: 'YOUTUBE_INVALID_URL',
  YOUTUBE_FETCH_ERROR: 'YOUTUBE_FETCH_ERROR',

  // 댓글 (Comment)
  COMMENT_FETCH_ERROR: 'COMMENT_FETCH_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
