export const routePages = {
  login: 'Login',
  mainTabs: 'MainTabs',
  contentDetail: 'ContentDetail',
  player: 'Player',
  channelDetail: 'ChannelDetail',
  search: 'Search',
  channelSelection: 'ChannelSelection',
  mediaList: 'MediaList',
  imageDetail: 'ImageDetail',
  profileSetup: 'ProfileSetup',
  settings: 'Settings',
  userContentList: 'UserContentList',
  quickExplore: 'QuickExplore',
  adminContentSearch: 'AdminContentSearch',
  adminPrimaryVideoSelect: 'AdminPrimaryVideoSelect',
  adminVideoManagement: 'AdminVideoManagement',
  adminUserManagement: 'AdminUserManagement',
  adminUserDetail: 'AdminUserDetail',
  adminPushContentSelect: 'AdminPushContentSelect',
  adminUserContentList: 'AdminUserContentList',
  adminContentRegistration: 'AdminContentRegistration',
} as const;

export type RoutePages = typeof routePages;
